### ISSUE TITLE
ERROR: change handler (update mail aliases) is not defined

### ISSUE THREAD

**Issue by tseropian** [equalitie/sec_comms#41]
Hello Equalit.ie team,

I'm testing Caislean on Debian 7 / Linode 4G VPS
I am having this error. Disappears the 2nd time I am pushing the playbook
<code>TASK: [common | Install /etc/aliases] ****************************************\* 
changed: [server.mydomain.com]
ERROR: change handler (update mail aliases) is not defined</code>

**Comment by willdoran** [comment]
@kheops2713 can you take a look at this?

**Comment by nosmo** [comment]
Hey @tseropian - thanks for the report. I've just pushed a commit that should address this issue.

**Comment by nosmo** [comment]
Resolving for now.
