### ISSUE TITLE
sysctl.yml tasks fail on first run against a clean Jessie installation

### ISSUE THREAD

**Issue by graphiclunarkid** [equalitie/sec_comms#51]
Reproduction steps:
1. Install a fresh version of Debian 8 (Jessie) on the target machine
2. Run the `common` role against this machine

Expected results

The tasks in the `sysctl.yml` playbook complete successfully.

Actual results

The `sysctl.yml` tasks fail the first time they are run against a new installation, but succeed the second and subsequent times. Possible race condition or timing issue with the previous task?

**Comment by kheops2713** [comment]
This should be solved with 2909cd401ebe0920ecd758482fb8ad3511d6aaf4. Basically using a retry.
