### ISSUE TITLE
RKHunter: whitelisting non-existent pathname prevents software installation and upgrade

### ISSUE THREAD

**Issue by graphiclunarkid** [equalitie/sec_comms#58]
### Reproduction steps
1. Run the `common` role against a Debian 8 (Jessie) machine that uses `grub-legacy` as its bootloader (e.g. a VPS running under the Xen hypervisor).
2. Use apt-get to install another program or upgrade existing programs.
### Expected result

The installation or upgrade completes successfully.
### Actual result

```
Invalid USER_FILEPROP_FILES_DIRS configuration option: Non-existent pathname: /boot/grub/*/*
E: Problem executing scripts DPkg::Post-Invoke 'if [ -x /usr/bin/rkhunter ] && grep -qiE '^APT_AUTOGEN=.?(true|yes)' /etc/default/rkhunter; then /usr/share/rkhunter/scripts/rkhupd.sh; fi'
E: Sub-process returned an error code
```
### Workaround

Remove the following line in /etc/rkhunter.conf.local

`USER_FILEPROP_FILES_DIRS=/boot/grub/*/*`

**Comment by graphiclunarkid** [comment]
I did some more testing to try to get to the bottom of this.

I can't reproduce the bug on a Debian 8 virtual machine on my localhost. In this environment `/boot/grub/` has three subdirectories: `fonts`, `i386-pc` and `locale`. Therefore RKHunter is happy because the pattern in the `rkhunter.conf.local` file exists. The installed version of grub is `grub2-pc`.

On a Debian 7 virtual machine, `/boot/grub/` also has subdirectories, but Caislean installs the original `rkhunter.conf` file rather than the new `rkhunter.conf.local`. The original file does not exclude `/boot/grub/*/*`in its `USER_FILEPROP_FILES_DIRS` parameter so RKHunter is happy because it is not trying to exclude a non-existent path:

`USER_FILEPROP_FILES_DIRS="/boot/* !/boot/*.dpkg-bak !/boot/lost+found !/boot/grub !/boot/grub/*"`

Testing on my real Debian 8 VPS produces the bug. That environment uses `grub-legacy` as its bootloader, and there are no subdirectories of `/boot/grub` in this version. Caislean's `rkhunter.conf.local` file for Debian 8 is looking for a path that doesn't exist so it throws an error.

My Debian 7 VPS also uses `grub-legacy`, but because Caislian's `wheezy-rkhunter.conf` file does not try to exclude `/boot/grub/*/*` in `USER_FILEPROP_FILES_DIRS` the bug does not appear.

It looks like we should be checking which version of grub is installed, not which version of Debian, and then including the `USER_FILEPROP_FILES_DIRS=/boot/grub/*/*` line in `rkhunter.conf.local` only if it is `grub2-pc`.

I have updated the reproduction steps to reflect the above.

**Comment by kheops2713** [comment]
Having met yet another situation of different /boot/ setup, plus a non-working default installation of rkhunter on Debian 8, I might restrict rkhunter to less checks or even remove it completely.

To check /boot/, this might be useful: https://github.com/grazzolini/chkboot

**Comment by kheops2713** [comment]
Rkhunter removed for now, commit f2742379ec549ec0989ccddd2ce230e62dee266d
