### ISSUE TITLE
Inconsistent change to RKHunter configuration

### ISSUE THREAD

**Issue by graphiclunarkid** [equalitie/sec_comms#59]
This is a question for @kheops2713.

The original Debian 7 RKHunter configuration, which we are still using for that OS, contains this line:

`USER_FILEPROP_FILES_DIRS="/boot/* !/boot/*.dpkg-bak !/boot/lost+found !/boot/grub !/boot/grub/*"`

This includes the files in `/boot/` in the file properties check and then excludes from the check some files and sub-directories contained within.

When I ported the `common` role to Debian 8 I found the syntax for including or excluding paths from the file properties check had changed. The correct syntax is now:

```
USER_FILEPROP_FILES_DIRS=/boot/*
EXCLUDE_USER_FILEPROP_FILES_DIRS=/boot/lost+found
EXCLUDE_USER_FILEPROP_FILES_DIRS=/boot/grub
EXCLUDE_USER_FILEPROP_FILES_DIRS=/boot/grub/*
```

The above configuration lines are functionally equivalent to the original configuration line.

In the current master branch, `rkhunter.conf.local` contains this instead:

```
USER_FILEPROP_FILES_DIRS=/boot/config-*
USER_FILEPROP_FILES_DIRS=/boot/initrd.img-*
USER_FILEPROP_FILES_DIRS=/boot/System.map-*
USER_FILEPROP_FILES_DIRS=/boot/vmlinuz-*
USER_FILEPROP_FILES_DIRS=/boot/grub/*
USER_FILEPROP_FILES_DIRS=/boot/grub/*/*
```

The last two lines of this (which include `/boot/grub/*` and `/boot/grub/*/*` in the check) are now opposite to the Debian 7 configuration (which excludes them). Is this a deliberate change? If so, should we make the same change in `wheezy-rkhunter.conf` so that Debian 7 systems behave the same way?

**Comment by kheops2713** [comment]
Rkhunter removed for now - f2742379ec549ec0989ccddd2ce230e62dee266d.
