### ISSUE TITLE
False positives by rkhunter

### ISSUE THREAD

**Issue by kheops2713** [equalitie/sec_comms#7]
- suricata listening on network interface
- a hidden process
- cron (and subprocesses) using a deleted file

**Comment by kheops2713** [comment]
Partly fixed with 47e6ba9951f212aa47d5a59459dff7dc9ae74e53 and dfbb0bd805bc0a8dd5d7428fcbdb0f101b0b899d that whitelist certain processes.

Still the hidden process to sort out.

**Comment by graphiclunarkid** [comment]
We removed rkhunter so this problem has now gone away.
